/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.Anagrafica;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AnagraficaRecord extends UpdatableRecordImpl<AnagraficaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.anagrafica.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.cognome_ragsoc</code>.
     */
    public void setCognomeRagsoc(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.cognome_ragsoc</code>.
     */
    public String getCognomeRagsoc() {
        return (String) get(1);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.nome</code>.
     */
    public void setNome(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.nome</code>.
     */
    public String getNome() {
        return (String) get(2);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.indirizzo</code>.
     */
    public void setIndirizzo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.indirizzo</code>.
     */
    public String getIndirizzo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.citta</code>.
     */
    public void setCitta(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.citta</code>.
     */
    public String getCitta() {
        return (String) get(4);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.provincia</code>.
     */
    public void setProvincia(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.provincia</code>.
     */
    public String getProvincia() {
        return (String) get(5);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.cap</code>.
     */
    public void setCap(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.cap</code>.
     */
    public String getCap() {
        return (String) get(6);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.piva</code>.
     */
    public void setPiva(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.piva</code>.
     */
    public String getPiva() {
        return (String) get(7);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.cf</code>.
     */
    public void setCf(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.cf</code>.
     */
    public String getCf() {
        return (String) get(8);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.telefono</code>.
     */
    public void setTelefono(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(9);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.peo</code>.
     */
    public void setPeo(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.peo</code>.
     */
    public String getPeo() {
        return (String) get(10);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.pec</code>.
     */
    public void setPec(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.pec</code>.
     */
    public String getPec() {
        return (String) get(11);
    }

    /**
     * Setter for <code>usrbilancio.anagrafica.giuridica</code>.
     */
    public void setGiuridica(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>usrbilancio.anagrafica.giuridica</code>.
     */
    public Boolean getGiuridica() {
        return (Boolean) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnagraficaRecord
     */
    public AnagraficaRecord() {
        super(Anagrafica.ANAGRAFICA);
    }

    /**
     * Create a detached, initialised AnagraficaRecord
     */
    public AnagraficaRecord(Integer id, String cognomeRagsoc, String nome, String indirizzo, String citta, String provincia, String cap, String piva, String cf, String telefono, String peo, String pec, Boolean giuridica) {
        super(Anagrafica.ANAGRAFICA);

        setId(id);
        setCognomeRagsoc(cognomeRagsoc);
        setNome(nome);
        setIndirizzo(indirizzo);
        setCitta(citta);
        setProvincia(provincia);
        setCap(cap);
        setPiva(piva);
        setCf(cf);
        setTelefono(telefono);
        setPeo(peo);
        setPec(pec);
        setGiuridica(giuridica);
        resetChangedOnNotNull();
    }
}
