/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.Capitolo;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CapitoloRecord extends UpdatableRecordImpl<CapitoloRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.capitolo.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.capitolo.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.capitolo.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.capitolo.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(1);
    }

    /**
     * Setter for <code>usrbilancio.capitolo.nuovoanno</code>.
     */
    public void setNuovoanno(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.capitolo.nuovoanno</code>.
     */
    public Byte getNuovoanno() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>usrbilancio.capitolo.daconsolidare</code>.
     */
    public void setDaconsolidare(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>usrbilancio.capitolo.daconsolidare</code>.
     */
    public Byte getDaconsolidare() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>usrbilancio.capitolo.stanziamento</code>.
     */
    public void setStanziamento(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>usrbilancio.capitolo.stanziamento</code>.
     */
    public BigDecimal getStanziamento() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>usrbilancio.capitolo.mostrasituazione</code>.
     */
    public void setMostrasituazione(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>usrbilancio.capitolo.mostrasituazione</code>.
     */
    public Byte getMostrasituazione() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>usrbilancio.capitolo.versione</code>.
     */
    public void setVersione(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>usrbilancio.capitolo.versione</code>.
     */
    public Long getVersione() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CapitoloRecord
     */
    public CapitoloRecord() {
        super(Capitolo.CAPITOLO);
    }

    /**
     * Create a detached, initialised CapitoloRecord
     */
    public CapitoloRecord(Integer id, String descrizione, Byte nuovoanno, Byte daconsolidare, BigDecimal stanziamento, Byte mostrasituazione, Long versione) {
        super(Capitolo.CAPITOLO);

        setId(id);
        setDescrizione(descrizione);
        setNuovoanno(nuovoanno);
        setDaconsolidare(daconsolidare);
        setStanziamento(stanziamento);
        setMostrasituazione(mostrasituazione);
        setVersione(versione);
        resetChangedOnNotNull();
    }
}
