/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.CodiciTributo;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodiciTributoRecord extends UpdatableRecordImpl<CodiciTributoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.codici_tributo.codice</code>.
     */
    public void setCodice(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.codici_tributo.codice</code>.
     */
    public String getCodice() {
        return (String) get(0);
    }

    /**
     * Setter for <code>usrbilancio.codici_tributo.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.codici_tributo.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodiciTributoRecord
     */
    public CodiciTributoRecord() {
        super(CodiciTributo.CODICI_TRIBUTO);
    }

    /**
     * Create a detached, initialised CodiciTributoRecord
     */
    public CodiciTributoRecord(String codice, String descrizione) {
        super(CodiciTributo.CODICI_TRIBUTO);

        setCodice(codice);
        setDescrizione(descrizione);
        resetChangedOnNotNull();
    }
}
