/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.Competenza;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 *     
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompetenzaRecord extends UpdatableRecordImpl<CompetenzaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.competenza.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.competenza.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.competenza.id_capitolo</code>.
     */
    public void setIdCapitolo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.competenza.id_capitolo</code>.
     */
    public Integer getIdCapitolo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>usrbilancio.competenza.anno</code>.
     */
    public void setAnno(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.competenza.anno</code>.
     */
    public Integer getAnno() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>usrbilancio.competenza.chiuso</code>.
     */
    public void setChiuso(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>usrbilancio.competenza.chiuso</code>.
     */
    public Byte getChiuso() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>usrbilancio.competenza.stanziamento</code>.
     */
    public void setStanziamento(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>usrbilancio.competenza.stanziamento</code>.
     */
    public BigDecimal getStanziamento() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>usrbilancio.competenza.note</code>.
     */
    public void setNote(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>usrbilancio.competenza.note</code>.
     */
    public String getNote() {
        return (String) get(5);
    }

    /**
     * Setter for <code>usrbilancio.competenza.versione</code>.
     */
    public void setVersione(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>usrbilancio.competenza.versione</code>.
     */
    public Long getVersione() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompetenzaRecord
     */
    public CompetenzaRecord() {
        super(Competenza.COMPETENZA);
    }

    /**
     * Create a detached, initialised CompetenzaRecord
     */
    public CompetenzaRecord(Integer id, Integer idCapitolo, Integer anno, Byte chiuso, BigDecimal stanziamento, String note, Long versione) {
        super(Competenza.COMPETENZA);

        setId(id);
        setIdCapitolo(idCapitolo);
        setAnno(anno);
        setChiuso(chiuso);
        setStanziamento(stanziamento);
        setNote(note);
        setVersione(versione);
        resetChangedOnNotNull();
    }
}
