/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.Comune;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ComuneRecord extends UpdatableRecordImpl<ComuneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.comune.cod_catastale</code>.
     */
    public void setCodCatastale(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.comune.cod_catastale</code>.
     */
    public String getCodCatastale() {
        return (String) get(0);
    }

    /**
     * Setter for <code>usrbilancio.comune.comune</code>.
     */
    public void setComune(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.comune.comune</code>.
     */
    public String getComune() {
        return (String) get(1);
    }

    /**
     * Setter for <code>usrbilancio.comune.prov</code>.
     */
    public void setProv(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.comune.prov</code>.
     */
    public String getProv() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ComuneRecord
     */
    public ComuneRecord() {
        super(Comune.COMUNE);
    }

    /**
     * Create a detached, initialised ComuneRecord
     */
    public ComuneRecord(String codCatastale, String comune, String prov) {
        super(Comune.COMUNE);

        setCodCatastale(codCatastale);
        setComune(comune);
        setProv(prov);
        resetChangedOnNotNull();
    }
}
