/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.Contabilita;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContabilitaRecord extends UpdatableRecordImpl<ContabilitaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.contabilita.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.contabilita.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.contabilita.numero</code>.
     */
    public void setNumero(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.contabilita.numero</code>.
     */
    public String getNumero() {
        return (String) get(1);
    }

    /**
     * Setter for <code>usrbilancio.contabilita.data_apertura</code>.
     */
    public void setDataApertura(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.contabilita.data_apertura</code>.
     */
    public LocalDate getDataApertura() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>usrbilancio.contabilita.data_chiusura</code>.
     */
    public void setDataChiusura(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>usrbilancio.contabilita.data_chiusura</code>.
     */
    public LocalDate getDataChiusura() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>usrbilancio.contabilita.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>usrbilancio.contabilita.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContabilitaRecord
     */
    public ContabilitaRecord() {
        super(Contabilita.CONTABILITA);
    }

    /**
     * Create a detached, initialised ContabilitaRecord
     */
    public ContabilitaRecord(Integer id, String numero, LocalDate dataApertura, LocalDate dataChiusura, String descrizione) {
        super(Contabilita.CONTABILITA);

        setId(id);
        setNumero(numero);
        setDataApertura(dataApertura);
        setDataChiusura(dataChiusura);
        setDescrizione(descrizione);
        resetChangedOnNotNull();
    }
}
