/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.MimeType;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MimeTypeRecord extends TableRecordImpl<MimeTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.mime_type.extension</code>.
     */
    public void setExtension(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.mime_type.extension</code>.
     */
    public String getExtension() {
        return (String) get(0);
    }

    /**
     * Setter for <code>usrbilancio.mime_type.mime</code>.
     */
    public void setMime(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.mime_type.mime</code>.
     */
    public String getMime() {
        return (String) get(1);
    }

    /**
     * Setter for <code>usrbilancio.mime_type.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.mime_type.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MimeTypeRecord
     */
    public MimeTypeRecord() {
        super(MimeType.MIME_TYPE);
    }

    /**
     * Create a detached, initialised MimeTypeRecord
     */
    public MimeTypeRecord(String extension, String mime, String descrizione) {
        super(MimeType.MIME_TYPE);

        setExtension(extension);
        setMime(mime);
        setDescrizione(descrizione);
        resetChangedOnNotNull();
    }
}
