/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.Modelli;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ModelliRecord extends UpdatableRecordImpl<ModelliRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.modelli.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.modelli.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.modelli.tipo</code>.
     */
    public void setTipo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.modelli.tipo</code>.
     */
    public String getTipo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>usrbilancio.modelli.nomefile</code>.
     */
    public void setNomefile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.modelli.nomefile</code>.
     */
    public String getNomefile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>usrbilancio.modelli.nomefile_locale</code>.
     */
    public void setNomefileLocale(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>usrbilancio.modelli.nomefile_locale</code>.
     */
    public String getNomefileLocale() {
        return (String) get(3);
    }

    /**
     * Setter for <code>usrbilancio.modelli.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>usrbilancio.modelli.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(4);
    }

    /**
     * Setter for <code>usrbilancio.modelli.data_pubblicazione</code>.
     */
    public void setDataPubblicazione(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>usrbilancio.modelli.data_pubblicazione</code>.
     */
    public LocalDateTime getDataPubblicazione() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelliRecord
     */
    public ModelliRecord() {
        super(Modelli.MODELLI);
    }

    /**
     * Create a detached, initialised ModelliRecord
     */
    public ModelliRecord(Integer id, String tipo, String nomefile, String nomefileLocale, String descrizione, LocalDateTime dataPubblicazione) {
        super(Modelli.MODELLI);

        setId(id);
        setTipo(tipo);
        setNomefile(nomefile);
        setNomefileLocale(nomefileLocale);
        setDescrizione(descrizione);
        setDataPubblicazione(dataPubblicazione);
        resetChangedOnNotNull();
    }
}
