/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.MovimentiVirtuali;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MovimentiVirtualiRecord extends UpdatableRecordImpl<MovimentiVirtualiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.id_competenza</code>.
     */
    public void setIdCompetenza(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.id_competenza</code>.
     */
    public Integer getIdCompetenza() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.id_codice</code>.
     */
    public void setIdCodice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.id_codice</code>.
     */
    public Integer getIdCodice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.id_tipo_documento</code>.
     */
    public void setIdTipoDocumento(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.id_tipo_documento</code>.
     */
    public Integer getIdTipoDocumento() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.numero_pagamento</code>.
     */
    public void setNumeroPagamento(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.numero_pagamento</code>.
     */
    public String getNumeroPagamento() {
        return (String) get(4);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.data_pagamento</code>.
     */
    public void setDataPagamento(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.data_pagamento</code>.
     */
    public LocalDate getDataPagamento() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.nominativo</code>.
     */
    public void setNominativo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.nominativo</code>.
     */
    public String getNominativo() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>usrbilancio.movimenti_virtuali.descrizione_ragioneria</code>.
     */
    public void setDescrizioneRagioneria(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>usrbilancio.movimenti_virtuali.descrizione_ragioneria</code>.
     */
    public String getDescrizioneRagioneria() {
        return (String) get(7);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.numero_documento</code>.
     */
    public void setNumeroDocumento(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.numero_documento</code>.
     */
    public String getNumeroDocumento() {
        return (String) get(8);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.data_documento</code>.
     */
    public void setDataDocumento(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.data_documento</code>.
     */
    public LocalDate getDataDocumento() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.importo</code>.
     */
    public void setImporto(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.importo</code>.
     */
    public BigDecimal getImporto() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.nomefile</code>.
     */
    public void setNomefile(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.nomefile</code>.
     */
    public String getNomefile() {
        return (String) get(11);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.nomefile_locale</code>.
     */
    public void setNomefileLocale(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.nomefile_locale</code>.
     */
    public String getNomefileLocale() {
        return (String) get(12);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.note</code>.
     */
    public void setNote(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.note</code>.
     */
    public String getNote() {
        return (String) get(13);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.flag</code>. 0 = nullo
     * 1 = commissario
     */
    public void setFlag(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.flag</code>. 0 = nullo
     * 1 = commissario
     */
    public Integer getFlag() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>usrbilancio.movimenti_virtuali.versione</code>.
     */
    public void setVersione(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>usrbilancio.movimenti_virtuali.versione</code>.
     */
    public Long getVersione() {
        return (Long) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovimentiVirtualiRecord
     */
    public MovimentiVirtualiRecord() {
        super(MovimentiVirtuali.MOVIMENTI_VIRTUALI);
    }

    /**
     * Create a detached, initialised MovimentiVirtualiRecord
     */
    public MovimentiVirtualiRecord(Integer id, Integer idCompetenza, Integer idCodice, Integer idTipoDocumento, String numeroPagamento, LocalDate dataPagamento, String nominativo, String descrizioneRagioneria, String numeroDocumento, LocalDate dataDocumento, BigDecimal importo, String nomefile, String nomefileLocale, String note, Integer flag, Long versione) {
        super(MovimentiVirtuali.MOVIMENTI_VIRTUALI);

        setId(id);
        setIdCompetenza(idCompetenza);
        setIdCodice(idCodice);
        setIdTipoDocumento(idTipoDocumento);
        setNumeroPagamento(numeroPagamento);
        setDataPagamento(dataPagamento);
        setNominativo(nominativo);
        setDescrizioneRagioneria(descrizioneRagioneria);
        setNumeroDocumento(numeroDocumento);
        setDataDocumento(dataDocumento);
        setImporto(importo);
        setNomefile(nomefile);
        setNomefileLocale(nomefileLocale);
        setNote(note);
        setFlag(flag);
        setVersione(versione);
        resetChangedOnNotNull();
    }
}
