/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.Parametri;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ParametriRecord extends UpdatableRecordImpl<ParametriRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.parametri.parametro</code>.
     */
    public void setParametro(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.parametri.parametro</code>.
     */
    public String getParametro() {
        return (String) get(0);
    }

    /**
     * Setter for <code>usrbilancio.parametri.valore</code>.
     */
    public void setValore(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.parametri.valore</code>.
     */
    public String getValore() {
        return (String) get(1);
    }

    /**
     * Setter for <code>usrbilancio.parametri.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.parametri.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParametriRecord
     */
    public ParametriRecord() {
        super(Parametri.PARAMETRI);
    }

    /**
     * Create a detached, initialised ParametriRecord
     */
    public ParametriRecord(String parametro, String valore, String descrizione) {
        super(Parametri.PARAMETRI);

        setParametro(parametro);
        setValore(valore);
        setDescrizione(descrizione);
        resetChangedOnNotNull();
    }
}
