/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.Quietanza;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class QuietanzaRecord extends UpdatableRecordImpl<QuietanzaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.quietanza.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.id_competenza</code>.
     */
    public void setIdCompetenza(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.id_competenza</code>.
     */
    public Integer getIdCompetenza() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.id_codice</code>.
     */
    public void setIdCodice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.id_codice</code>.
     */
    public Integer getIdCodice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.id_tipo_rts</code>.
     */
    public void setIdTipoRts(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.id_tipo_rts</code>.
     */
    public Integer getIdTipoRts() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.id_tipo_documento</code>.
     */
    public void setIdTipoDocumento(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.id_tipo_documento</code>.
     */
    public Integer getIdTipoDocumento() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.numero_documento</code>.
     */
    public void setNumeroDocumento(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.numero_documento</code>.
     */
    public String getNumeroDocumento() {
        return (String) get(5);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.data_documento</code>.
     */
    public void setDataDocumento(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.data_documento</code>.
     */
    public LocalDate getDataDocumento() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.numero_pagamento</code>.
     */
    public void setNumeroPagamento(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.numero_pagamento</code>.
     */
    public String getNumeroPagamento() {
        return (String) get(7);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.data_pagamento</code>.
     */
    public void setDataPagamento(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.data_pagamento</code>.
     */
    public LocalDate getDataPagamento() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.ordinante</code>.
     */
    public void setOrdinante(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.ordinante</code>.
     */
    public String getOrdinante() {
        return (String) get(9);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.descrizione_ordinanza</code>.
     */
    public void setDescrizioneOrdinanza(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.descrizione_ordinanza</code>.
     */
    public String getDescrizioneOrdinanza() {
        return (String) get(10);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.importo</code>.
     */
    public void setImporto(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.importo</code>.
     */
    public BigDecimal getImporto() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.nomefile</code>.
     */
    public void setNomefile(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.nomefile</code>.
     */
    public String getNomefile() {
        return (String) get(12);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.nomefile_locale</code>.
     */
    public void setNomefileLocale(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.nomefile_locale</code>.
     */
    public String getNomefileLocale() {
        return (String) get(13);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.note</code>.
     */
    public void setNote(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.note</code>.
     */
    public String getNote() {
        return (String) get(14);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.flag</code>. 0 = nullo
     * 1 = commissario
     */
    public void setFlag(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.flag</code>. 0 = nullo
     * 1 = commissario
     */
    public Integer getFlag() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>usrbilancio.quietanza.versione</code>.
     */
    public void setVersione(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>usrbilancio.quietanza.versione</code>.
     */
    public Long getVersione() {
        return (Long) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuietanzaRecord
     */
    public QuietanzaRecord() {
        super(Quietanza.QUIETANZA);
    }

    /**
     * Create a detached, initialised QuietanzaRecord
     */
    public QuietanzaRecord(Integer id, Integer idCompetenza, Integer idCodice, Integer idTipoRts, Integer idTipoDocumento, String numeroDocumento, LocalDate dataDocumento, String numeroPagamento, LocalDate dataPagamento, String ordinante, String descrizioneOrdinanza, BigDecimal importo, String nomefile, String nomefileLocale, String note, Integer flag, Long versione) {
        super(Quietanza.QUIETANZA);

        setId(id);
        setIdCompetenza(idCompetenza);
        setIdCodice(idCodice);
        setIdTipoRts(idTipoRts);
        setIdTipoDocumento(idTipoDocumento);
        setNumeroDocumento(numeroDocumento);
        setDataDocumento(dataDocumento);
        setNumeroPagamento(numeroPagamento);
        setDataPagamento(dataPagamento);
        setOrdinante(ordinante);
        setDescrizioneOrdinanza(descrizioneOrdinanza);
        setImporto(importo);
        setNomefile(nomefile);
        setNomefileLocale(nomefileLocale);
        setNote(note);
        setFlag(flag);
        setVersione(versione);
        resetChangedOnNotNull();
    }
}
