/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.RettificaIva;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RettificaIvaRecord extends UpdatableRecordImpl<RettificaIvaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.rettifica_iva.anno</code>.
     */
    public void setAnno(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.rettifica_iva.anno</code>.
     */
    public Integer getAnno() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.rettifica_iva.iva_anagrafica</code>.
     */
    public void setIvaAnagrafica(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.rettifica_iva.iva_anagrafica</code>.
     */
    public BigDecimal getIvaAnagrafica() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>usrbilancio.rettifica_iva.iva_pagata</code>.
     */
    public void setIvaPagata(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.rettifica_iva.iva_pagata</code>.
     */
    public BigDecimal getIvaPagata() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RettificaIvaRecord
     */
    public RettificaIvaRecord() {
        super(RettificaIva.RETTIFICA_IVA);
    }

    /**
     * Create a detached, initialised RettificaIvaRecord
     */
    public RettificaIvaRecord(Integer anno, BigDecimal ivaAnagrafica, BigDecimal ivaPagata) {
        super(RettificaIva.RETTIFICA_IVA);

        setAnno(anno);
        setIvaAnagrafica(ivaAnagrafica);
        setIvaPagata(ivaPagata);
        resetChangedOnNotNull();
    }
}
