/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.Ritenuta;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 *     
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RitenutaRecord extends UpdatableRecordImpl<RitenutaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.ritenuta.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.ritenuta.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.ritenuta.id_ordinativo</code>.
     */
    public void setIdOrdinativo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.ritenuta.id_ordinativo</code>.
     */
    public Integer getIdOrdinativo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>usrbilancio.ritenuta.id_anagrafica</code>.
     */
    public void setIdAnagrafica(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.ritenuta.id_anagrafica</code>.
     */
    public Integer getIdAnagrafica() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>usrbilancio.ritenuta.imponibile</code>.
     */
    public void setImponibile(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>usrbilancio.ritenuta.imponibile</code>.
     */
    public BigDecimal getImponibile() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>usrbilancio.ritenuta.cassa</code>.
     */
    public void setCassa(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>usrbilancio.ritenuta.cassa</code>.
     */
    public BigDecimal getCassa() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>usrbilancio.ritenuta.spese_anticipo</code>.
     */
    public void setSpeseAnticipo(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>usrbilancio.ritenuta.spese_anticipo</code>.
     */
    public BigDecimal getSpeseAnticipo() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>usrbilancio.ritenuta.iva</code>.
     */
    public void setIva(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>usrbilancio.ritenuta.iva</code>.
     */
    public BigDecimal getIva() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>usrbilancio.ritenuta.perc_ritenute_operate</code>.
     */
    public void setPercRitenuteOperate(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>usrbilancio.ritenuta.perc_ritenute_operate</code>.
     */
    public BigDecimal getPercRitenuteOperate() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>usrbilancio.ritenuta.perc_irap_versata</code>.
     */
    public void setPercIrapVersata(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>usrbilancio.ritenuta.perc_irap_versata</code>.
     */
    public BigDecimal getPercIrapVersata() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>usrbilancio.ritenuta.versione</code>.
     */
    public void setVersione(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>usrbilancio.ritenuta.versione</code>.
     */
    public Long getVersione() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RitenutaRecord
     */
    public RitenutaRecord() {
        super(Ritenuta.RITENUTA);
    }

    /**
     * Create a detached, initialised RitenutaRecord
     */
    public RitenutaRecord(Integer id, Integer idOrdinativo, Integer idAnagrafica, BigDecimal imponibile, BigDecimal cassa, BigDecimal speseAnticipo, BigDecimal iva, BigDecimal percRitenuteOperate, BigDecimal percIrapVersata, Long versione) {
        super(Ritenuta.RITENUTA);

        setId(id);
        setIdOrdinativo(idOrdinativo);
        setIdAnagrafica(idAnagrafica);
        setImponibile(imponibile);
        setCassa(cassa);
        setSpeseAnticipo(speseAnticipo);
        setIva(iva);
        setPercRitenuteOperate(percRitenuteOperate);
        setPercIrapVersata(percIrapVersata);
        setVersione(versione);
        resetChangedOnNotNull();
    }
}
