/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.TipoRts;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TipoRtsRecord extends UpdatableRecordImpl<TipoRtsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.tipo_rts.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.tipo_rts.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.tipo_rts.codice</code>.
     */
    public void setCodice(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.tipo_rts.codice</code>.
     */
    public String getCodice() {
        return (String) get(1);
    }

    /**
     * Setter for <code>usrbilancio.tipo_rts.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.tipo_rts.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TipoRtsRecord
     */
    public TipoRtsRecord() {
        super(TipoRts.TIPO_RTS);
    }

    /**
     * Create a detached, initialised TipoRtsRecord
     */
    public TipoRtsRecord(Integer id, String codice, String descrizione) {
        super(TipoRts.TIPO_RTS);

        setId(id);
        setCodice(codice);
        setDescrizione(descrizione);
        resetChangedOnNotNull();
    }
}
