/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.TipoDocumento;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TipoDocumentoRecord extends UpdatableRecordImpl<TipoDocumentoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.tipo_documento.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.tipo_documento.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usrbilancio.tipo_documento.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.tipo_documento.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(1);
    }

    /**
     * Setter for <code>usrbilancio.tipo_documento.stampabile</code>.
     */
    public void setStampabile(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.tipo_documento.stampabile</code>.
     */
    public Byte getStampabile() {
        return (Byte) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TipoDocumentoRecord
     */
    public TipoDocumentoRecord() {
        super(TipoDocumento.TIPO_DOCUMENTO);
    }

    /**
     * Create a detached, initialised TipoDocumentoRecord
     */
    public TipoDocumentoRecord(Integer id, String descrizione, Byte stampabile) {
        super(TipoDocumento.TIPO_DOCUMENTO);

        setId(id);
        setDescrizione(descrizione);
        setStampabile(stampabile);
        resetChangedOnNotNull();
    }
}
