/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.Utente;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UtenteRecord extends UpdatableRecordImpl<UtenteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>usrbilancio.utente.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>usrbilancio.utente.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>usrbilancio.utente.abilitato</code>.
     */
    public void setAbilitato(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>usrbilancio.utente.abilitato</code>.
     */
    public Byte getAbilitato() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>usrbilancio.utente.admin</code>.
     */
    public void setAdmin(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>usrbilancio.utente.admin</code>.
     */
    public Byte getAdmin() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>usrbilancio.utente.gender</code>.
     */
    public void setGender(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>usrbilancio.utente.gender</code>.
     */
    public String getGender() {
        return (String) get(3);
    }

    /**
     * Setter for <code>usrbilancio.utente.pubblica</code>.
     */
    public void setPubblica(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>usrbilancio.utente.pubblica</code>.
     */
    public Byte getPubblica() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UtenteRecord
     */
    public UtenteRecord() {
        super(Utente.UTENTE);
    }

    /**
     * Create a detached, initialised UtenteRecord
     */
    public UtenteRecord(String username, Byte abilitato, Byte admin, String gender, Byte pubblica) {
        super(Utente.UTENTE);

        setUsername(username);
        setAbilitato(abilitato);
        setAdmin(admin);
        setGender(gender);
        setPubblica(pubblica);
        resetChangedOnNotNull();
    }
}
