/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables.records;


import it.usr.web.usrbilancio.domain.tables.VRitenute;

import org.jooq.impl.TableRecordImpl;


/**
 * View 'usrbilancio.v_ritenute' references invalid table(s) or column(s) or
 * function(s) or definer/invoker of view lack rights to use them
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VRitenuteRecord extends TableRecordImpl<VRitenuteRecord> {

    private static final long serialVersionUID = 1L;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VRitenuteRecord
     */
    public VRitenuteRecord() {
        super(VRitenute.V_RITENUTE);
    }
}
