/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables;


import it.usr.web.usrbilancio.domain.Indexes;
import it.usr.web.usrbilancio.domain.Keys;
import it.usr.web.usrbilancio.domain.Usrbilancio;
import it.usr.web.usrbilancio.domain.tables.Codice.CodicePath;
import it.usr.web.usrbilancio.domain.tables.records.AllegatoCodiceRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AllegatoCodice extends TableImpl<AllegatoCodiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>usrbilancio.allegato_codice</code>
     */
    public static final AllegatoCodice ALLEGATO_CODICE = new AllegatoCodice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AllegatoCodiceRecord> getRecordType() {
        return AllegatoCodiceRecord.class;
    }

    /**
     * The column <code>usrbilancio.allegato_codice.id</code>.
     */
    public final TableField<AllegatoCodiceRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>usrbilancio.allegato_codice.id_codice</code>.
     */
    public final TableField<AllegatoCodiceRecord, Integer> ID_CODICE = createField(DSL.name("id_codice"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>usrbilancio.allegato_codice.gruppo</code>.
     */
    public final TableField<AllegatoCodiceRecord, String> GRUPPO = createField(DSL.name("gruppo"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>usrbilancio.allegato_codice.nomefile</code>.
     */
    public final TableField<AllegatoCodiceRecord, String> NOMEFILE = createField(DSL.name("nomefile"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.allegato_codice.nomefile_locale</code>.
     */
    public final TableField<AllegatoCodiceRecord, String> NOMEFILE_LOCALE = createField(DSL.name("nomefile_locale"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.allegato_codice.descrizione</code>.
     */
    public final TableField<AllegatoCodiceRecord, String> DESCRIZIONE = createField(DSL.name("descrizione"), SQLDataType.VARCHAR(255), this, "");

    private AllegatoCodice(Name alias, Table<AllegatoCodiceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AllegatoCodice(Name alias, Table<AllegatoCodiceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>usrbilancio.allegato_codice</code> table
     * reference
     */
    public AllegatoCodice(String alias) {
        this(DSL.name(alias), ALLEGATO_CODICE);
    }

    /**
     * Create an aliased <code>usrbilancio.allegato_codice</code> table
     * reference
     */
    public AllegatoCodice(Name alias) {
        this(alias, ALLEGATO_CODICE);
    }

    /**
     * Create a <code>usrbilancio.allegato_codice</code> table reference
     */
    public AllegatoCodice() {
        this(DSL.name("allegato_codice"), null);
    }

    public <O extends Record> AllegatoCodice(Table<O> path, ForeignKey<O, AllegatoCodiceRecord> childPath, InverseForeignKey<O, AllegatoCodiceRecord> parentPath) {
        super(path, childPath, parentPath, ALLEGATO_CODICE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AllegatoCodicePath extends AllegatoCodice implements Path<AllegatoCodiceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AllegatoCodicePath(Table<O> path, ForeignKey<O, AllegatoCodiceRecord> childPath, InverseForeignKey<O, AllegatoCodiceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AllegatoCodicePath(Name alias, Table<AllegatoCodiceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AllegatoCodicePath as(String alias) {
            return new AllegatoCodicePath(DSL.name(alias), this);
        }

        @Override
        public AllegatoCodicePath as(Name alias) {
            return new AllegatoCodicePath(alias, this);
        }

        @Override
        public AllegatoCodicePath as(Table<?> alias) {
            return new AllegatoCodicePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Usrbilancio.USRBILANCIO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ALLEGATO_CODICE_FK_ALLEGATOCODICE_CODICE_IDX);
    }

    @Override
    public Identity<AllegatoCodiceRecord, Integer> getIdentity() {
        return (Identity<AllegatoCodiceRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AllegatoCodiceRecord> getPrimaryKey() {
        return Keys.KEY_ALLEGATO_CODICE_PRIMARY;
    }

    @Override
    public List<ForeignKey<AllegatoCodiceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ALLEGATOCODICE_CODICE);
    }

    private transient CodicePath _codice;

    /**
     * Get the implicit join path to the <code>usrbilancio.codice</code> table.
     */
    public CodicePath codice() {
        if (_codice == null)
            _codice = new CodicePath(this, Keys.FK_ALLEGATOCODICE_CODICE, null);

        return _codice;
    }

    @Override
    public AllegatoCodice as(String alias) {
        return new AllegatoCodice(DSL.name(alias), this);
    }

    @Override
    public AllegatoCodice as(Name alias) {
        return new AllegatoCodice(alias, this);
    }

    @Override
    public AllegatoCodice as(Table<?> alias) {
        return new AllegatoCodice(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AllegatoCodice rename(String name) {
        return new AllegatoCodice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AllegatoCodice rename(Name name) {
        return new AllegatoCodice(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AllegatoCodice rename(Table<?> name) {
        return new AllegatoCodice(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllegatoCodice where(Condition condition) {
        return new AllegatoCodice(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllegatoCodice where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllegatoCodice where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllegatoCodice where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AllegatoCodice where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AllegatoCodice where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AllegatoCodice where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AllegatoCodice where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllegatoCodice whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllegatoCodice whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
