/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables;


import it.usr.web.usrbilancio.domain.Keys;
import it.usr.web.usrbilancio.domain.Usrbilancio;
import it.usr.web.usrbilancio.domain.tables.Ritenuta.RitenutaPath;
import it.usr.web.usrbilancio.domain.tables.records.AnagraficaRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Anagrafica extends TableImpl<AnagraficaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>usrbilancio.anagrafica</code>
     */
    public static final Anagrafica ANAGRAFICA = new Anagrafica();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AnagraficaRecord> getRecordType() {
        return AnagraficaRecord.class;
    }

    /**
     * The column <code>usrbilancio.anagrafica.id</code>.
     */
    public final TableField<AnagraficaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.cognome_ragsoc</code>.
     */
    public final TableField<AnagraficaRecord, String> COGNOME_RAGSOC = createField(DSL.name("cognome_ragsoc"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.nome</code>.
     */
    public final TableField<AnagraficaRecord, String> NOME = createField(DSL.name("nome"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.indirizzo</code>.
     */
    public final TableField<AnagraficaRecord, String> INDIRIZZO = createField(DSL.name("indirizzo"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.citta</code>.
     */
    public final TableField<AnagraficaRecord, String> CITTA = createField(DSL.name("citta"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.provincia</code>.
     */
    public final TableField<AnagraficaRecord, String> PROVINCIA = createField(DSL.name("provincia"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.cap</code>.
     */
    public final TableField<AnagraficaRecord, String> CAP = createField(DSL.name("cap"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.codice_catastale</code>.
     */
    public final TableField<AnagraficaRecord, String> CODICE_CATASTALE = createField(DSL.name("codice_catastale"), SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.piva</code>.
     */
    public final TableField<AnagraficaRecord, String> PIVA = createField(DSL.name("piva"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.cf</code>.
     */
    public final TableField<AnagraficaRecord, String> CF = createField(DSL.name("cf"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.telefono</code>.
     */
    public final TableField<AnagraficaRecord, String> TELEFONO = createField(DSL.name("telefono"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.peo</code>.
     */
    public final TableField<AnagraficaRecord, String> PEO = createField(DSL.name("peo"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.pec</code>.
     */
    public final TableField<AnagraficaRecord, String> PEC = createField(DSL.name("pec"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.giuridica</code>.
     */
    public final TableField<AnagraficaRecord, Boolean> GIURIDICA = createField(DSL.name("giuridica"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>usrbilancio.anagrafica.versione</code>.
     */
    public final TableField<AnagraficaRecord, Long> VERSIONE = createField(DSL.name("versione"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    private Anagrafica(Name alias, Table<AnagraficaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Anagrafica(Name alias, Table<AnagraficaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>usrbilancio.anagrafica</code> table reference
     */
    public Anagrafica(String alias) {
        this(DSL.name(alias), ANAGRAFICA);
    }

    /**
     * Create an aliased <code>usrbilancio.anagrafica</code> table reference
     */
    public Anagrafica(Name alias) {
        this(alias, ANAGRAFICA);
    }

    /**
     * Create a <code>usrbilancio.anagrafica</code> table reference
     */
    public Anagrafica() {
        this(DSL.name("anagrafica"), null);
    }

    public <O extends Record> Anagrafica(Table<O> path, ForeignKey<O, AnagraficaRecord> childPath, InverseForeignKey<O, AnagraficaRecord> parentPath) {
        super(path, childPath, parentPath, ANAGRAFICA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AnagraficaPath extends Anagrafica implements Path<AnagraficaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AnagraficaPath(Table<O> path, ForeignKey<O, AnagraficaRecord> childPath, InverseForeignKey<O, AnagraficaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AnagraficaPath(Name alias, Table<AnagraficaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AnagraficaPath as(String alias) {
            return new AnagraficaPath(DSL.name(alias), this);
        }

        @Override
        public AnagraficaPath as(Name alias) {
            return new AnagraficaPath(alias, this);
        }

        @Override
        public AnagraficaPath as(Table<?> alias) {
            return new AnagraficaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Usrbilancio.USRBILANCIO;
    }

    @Override
    public Identity<AnagraficaRecord, Integer> getIdentity() {
        return (Identity<AnagraficaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AnagraficaRecord> getPrimaryKey() {
        return Keys.KEY_ANAGRAFICA_PRIMARY;
    }

    private transient RitenutaPath _ritenuta;

    /**
     * Get the implicit to-many join path to the
     * <code>usrbilancio.ritenuta</code> table
     */
    public RitenutaPath ritenuta() {
        if (_ritenuta == null)
            _ritenuta = new RitenutaPath(this, null, Keys.FK_RITENUTA_ANAGRAFICA.getInverseKey());

        return _ritenuta;
    }

    @Override
    public Anagrafica as(String alias) {
        return new Anagrafica(DSL.name(alias), this);
    }

    @Override
    public Anagrafica as(Name alias) {
        return new Anagrafica(alias, this);
    }

    @Override
    public Anagrafica as(Table<?> alias) {
        return new Anagrafica(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Anagrafica rename(String name) {
        return new Anagrafica(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Anagrafica rename(Name name) {
        return new Anagrafica(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Anagrafica rename(Table<?> name) {
        return new Anagrafica(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Anagrafica where(Condition condition) {
        return new Anagrafica(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Anagrafica where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Anagrafica where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Anagrafica where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Anagrafica where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Anagrafica where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Anagrafica where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Anagrafica where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Anagrafica whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Anagrafica whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
