/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables;


import it.usr.web.usrbilancio.domain.Keys;
import it.usr.web.usrbilancio.domain.Usrbilancio;
import it.usr.web.usrbilancio.domain.tables.records.CodiciTributoRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodiciTributo extends TableImpl<CodiciTributoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>usrbilancio.codici_tributo</code>
     */
    public static final CodiciTributo CODICI_TRIBUTO = new CodiciTributo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodiciTributoRecord> getRecordType() {
        return CodiciTributoRecord.class;
    }

    /**
     * The column <code>usrbilancio.codici_tributo.codice</code>.
     */
    public final TableField<CodiciTributoRecord, String> CODICE = createField(DSL.name("codice"), SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.codici_tributo.descrizione</code>.
     */
    public final TableField<CodiciTributoRecord, String> DESCRIZIONE = createField(DSL.name("descrizione"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private CodiciTributo(Name alias, Table<CodiciTributoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodiciTributo(Name alias, Table<CodiciTributoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>usrbilancio.codici_tributo</code> table reference
     */
    public CodiciTributo(String alias) {
        this(DSL.name(alias), CODICI_TRIBUTO);
    }

    /**
     * Create an aliased <code>usrbilancio.codici_tributo</code> table reference
     */
    public CodiciTributo(Name alias) {
        this(alias, CODICI_TRIBUTO);
    }

    /**
     * Create a <code>usrbilancio.codici_tributo</code> table reference
     */
    public CodiciTributo() {
        this(DSL.name("codici_tributo"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Usrbilancio.USRBILANCIO;
    }

    @Override
    public UniqueKey<CodiciTributoRecord> getPrimaryKey() {
        return Keys.KEY_CODICI_TRIBUTO_PRIMARY;
    }

    @Override
    public CodiciTributo as(String alias) {
        return new CodiciTributo(DSL.name(alias), this);
    }

    @Override
    public CodiciTributo as(Name alias) {
        return new CodiciTributo(alias, this);
    }

    @Override
    public CodiciTributo as(Table<?> alias) {
        return new CodiciTributo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodiciTributo rename(String name) {
        return new CodiciTributo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodiciTributo rename(Name name) {
        return new CodiciTributo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodiciTributo rename(Table<?> name) {
        return new CodiciTributo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodiciTributo where(Condition condition) {
        return new CodiciTributo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodiciTributo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodiciTributo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodiciTributo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodiciTributo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodiciTributo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodiciTributo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodiciTributo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodiciTributo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodiciTributo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
