/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables;


import it.usr.web.usrbilancio.domain.Keys;
import it.usr.web.usrbilancio.domain.Usrbilancio;
import it.usr.web.usrbilancio.domain.tables.records.ComuneRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Comune extends TableImpl<ComuneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>usrbilancio.comune</code>
     */
    public static final Comune COMUNE = new Comune();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ComuneRecord> getRecordType() {
        return ComuneRecord.class;
    }

    /**
     * The column <code>usrbilancio.comune.cod_catastale</code>.
     */
    public final TableField<ComuneRecord, String> COD_CATASTALE = createField(DSL.name("cod_catastale"), SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.comune.comune</code>.
     */
    public final TableField<ComuneRecord, String> COMUNE_ = createField(DSL.name("comune"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.comune.prov</code>.
     */
    public final TableField<ComuneRecord, String> PROV = createField(DSL.name("prov"), SQLDataType.VARCHAR(2).nullable(false), this, "");

    private Comune(Name alias, Table<ComuneRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Comune(Name alias, Table<ComuneRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>usrbilancio.comune</code> table reference
     */
    public Comune(String alias) {
        this(DSL.name(alias), COMUNE);
    }

    /**
     * Create an aliased <code>usrbilancio.comune</code> table reference
     */
    public Comune(Name alias) {
        this(alias, COMUNE);
    }

    /**
     * Create a <code>usrbilancio.comune</code> table reference
     */
    public Comune() {
        this(DSL.name("comune"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Usrbilancio.USRBILANCIO;
    }

    @Override
    public UniqueKey<ComuneRecord> getPrimaryKey() {
        return Keys.KEY_COMUNE_PRIMARY;
    }

    @Override
    public Comune as(String alias) {
        return new Comune(DSL.name(alias), this);
    }

    @Override
    public Comune as(Name alias) {
        return new Comune(alias, this);
    }

    @Override
    public Comune as(Table<?> alias) {
        return new Comune(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Comune rename(String name) {
        return new Comune(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Comune rename(Name name) {
        return new Comune(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Comune rename(Table<?> name) {
        return new Comune(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comune where(Condition condition) {
        return new Comune(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comune where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comune where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comune where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Comune where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Comune where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Comune where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Comune where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comune whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Comune whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
