/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables;


import it.usr.web.usrbilancio.domain.Keys;
import it.usr.web.usrbilancio.domain.Usrbilancio;
import it.usr.web.usrbilancio.domain.tables.Capitolo.CapitoloPath;
import it.usr.web.usrbilancio.domain.tables.Codice.CodicePath;
import it.usr.web.usrbilancio.domain.tables.OrdinativoAppoggio.OrdinativoAppoggioPath;
import it.usr.web.usrbilancio.domain.tables.RettificaIva.RettificaIvaPath;
import it.usr.web.usrbilancio.domain.tables.records.ContabilitaRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Contabilita extends TableImpl<ContabilitaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>usrbilancio.contabilita</code>
     */
    public static final Contabilita CONTABILITA = new Contabilita();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContabilitaRecord> getRecordType() {
        return ContabilitaRecord.class;
    }

    /**
     * The column <code>usrbilancio.contabilita.id</code>.
     */
    public final TableField<ContabilitaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>usrbilancio.contabilita.numero</code>.
     */
    public final TableField<ContabilitaRecord, String> NUMERO = createField(DSL.name("numero"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.contabilita.data_apertura</code>.
     */
    public final TableField<ContabilitaRecord, LocalDate> DATA_APERTURA = createField(DSL.name("data_apertura"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>usrbilancio.contabilita.data_chiusura</code>.
     */
    public final TableField<ContabilitaRecord, LocalDate> DATA_CHIUSURA = createField(DSL.name("data_chiusura"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>usrbilancio.contabilita.descrizione</code>.
     */
    public final TableField<ContabilitaRecord, String> DESCRIZIONE = createField(DSL.name("descrizione"), SQLDataType.VARCHAR(255), this, "");

    private Contabilita(Name alias, Table<ContabilitaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Contabilita(Name alias, Table<ContabilitaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>usrbilancio.contabilita</code> table reference
     */
    public Contabilita(String alias) {
        this(DSL.name(alias), CONTABILITA);
    }

    /**
     * Create an aliased <code>usrbilancio.contabilita</code> table reference
     */
    public Contabilita(Name alias) {
        this(alias, CONTABILITA);
    }

    /**
     * Create a <code>usrbilancio.contabilita</code> table reference
     */
    public Contabilita() {
        this(DSL.name("contabilita"), null);
    }

    public <O extends Record> Contabilita(Table<O> path, ForeignKey<O, ContabilitaRecord> childPath, InverseForeignKey<O, ContabilitaRecord> parentPath) {
        super(path, childPath, parentPath, CONTABILITA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ContabilitaPath extends Contabilita implements Path<ContabilitaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ContabilitaPath(Table<O> path, ForeignKey<O, ContabilitaRecord> childPath, InverseForeignKey<O, ContabilitaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ContabilitaPath(Name alias, Table<ContabilitaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ContabilitaPath as(String alias) {
            return new ContabilitaPath(DSL.name(alias), this);
        }

        @Override
        public ContabilitaPath as(Name alias) {
            return new ContabilitaPath(alias, this);
        }

        @Override
        public ContabilitaPath as(Table<?> alias) {
            return new ContabilitaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Usrbilancio.USRBILANCIO;
    }

    @Override
    public Identity<ContabilitaRecord, Integer> getIdentity() {
        return (Identity<ContabilitaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ContabilitaRecord> getPrimaryKey() {
        return Keys.KEY_CONTABILITA_PRIMARY;
    }

    @Override
    public List<UniqueKey<ContabilitaRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_CONTABILITA_NUMERO_UNIQUE);
    }

    private transient CapitoloPath _capitolo;

    /**
     * Get the implicit to-many join path to the
     * <code>usrbilancio.capitolo</code> table
     */
    public CapitoloPath capitolo() {
        if (_capitolo == null)
            _capitolo = new CapitoloPath(this, null, Keys.FK_CAPITOLO_CONTABILITA.getInverseKey());

        return _capitolo;
    }

    private transient CodicePath _codice;

    /**
     * Get the implicit to-many join path to the <code>usrbilancio.codice</code>
     * table
     */
    public CodicePath codice() {
        if (_codice == null)
            _codice = new CodicePath(this, null, Keys.FK_CODICE_CONTABILITA.getInverseKey());

        return _codice;
    }

    private transient OrdinativoAppoggioPath _ordinativoAppoggio;

    /**
     * Get the implicit to-many join path to the
     * <code>usrbilancio.ordinativo_appoggio</code> table
     */
    public OrdinativoAppoggioPath ordinativoAppoggio() {
        if (_ordinativoAppoggio == null)
            _ordinativoAppoggio = new OrdinativoAppoggioPath(this, null, Keys.FK_ORDINATIVOAPP_CONTABILITA.getInverseKey());

        return _ordinativoAppoggio;
    }

    private transient RettificaIvaPath _rettificaIva;

    /**
     * Get the implicit to-many join path to the
     * <code>usrbilancio.rettifica_iva</code> table
     */
    public RettificaIvaPath rettificaIva() {
        if (_rettificaIva == null)
            _rettificaIva = new RettificaIvaPath(this, null, Keys.FK_RETTIFICAIVA_CONTABILITA.getInverseKey());

        return _rettificaIva;
    }

    @Override
    public Contabilita as(String alias) {
        return new Contabilita(DSL.name(alias), this);
    }

    @Override
    public Contabilita as(Name alias) {
        return new Contabilita(alias, this);
    }

    @Override
    public Contabilita as(Table<?> alias) {
        return new Contabilita(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Contabilita rename(String name) {
        return new Contabilita(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Contabilita rename(Name name) {
        return new Contabilita(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Contabilita rename(Table<?> name) {
        return new Contabilita(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contabilita where(Condition condition) {
        return new Contabilita(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contabilita where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contabilita where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contabilita where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contabilita where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contabilita where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contabilita where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contabilita where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contabilita whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contabilita whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
