/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables;


import it.usr.web.usrbilancio.domain.Keys;
import it.usr.web.usrbilancio.domain.Usrbilancio;
import it.usr.web.usrbilancio.domain.tables.records.ModelliRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Modelli extends TableImpl<ModelliRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>usrbilancio.modelli</code>
     */
    public static final Modelli MODELLI = new Modelli();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ModelliRecord> getRecordType() {
        return ModelliRecord.class;
    }

    /**
     * The column <code>usrbilancio.modelli.id</code>.
     */
    public final TableField<ModelliRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>usrbilancio.modelli.tipo</code>.
     */
    public final TableField<ModelliRecord, String> TIPO = createField(DSL.name("tipo"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.modelli.nomefile</code>.
     */
    public final TableField<ModelliRecord, String> NOMEFILE = createField(DSL.name("nomefile"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.modelli.nomefile_locale</code>.
     */
    public final TableField<ModelliRecord, String> NOMEFILE_LOCALE = createField(DSL.name("nomefile_locale"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.modelli.descrizione</code>.
     */
    public final TableField<ModelliRecord, String> DESCRIZIONE = createField(DSL.name("descrizione"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.modelli.data_pubblicazione</code>.
     */
    public final TableField<ModelliRecord, LocalDateTime> DATA_PUBBLICAZIONE = createField(DSL.name("data_pubblicazione"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    private Modelli(Name alias, Table<ModelliRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Modelli(Name alias, Table<ModelliRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>usrbilancio.modelli</code> table reference
     */
    public Modelli(String alias) {
        this(DSL.name(alias), MODELLI);
    }

    /**
     * Create an aliased <code>usrbilancio.modelli</code> table reference
     */
    public Modelli(Name alias) {
        this(alias, MODELLI);
    }

    /**
     * Create a <code>usrbilancio.modelli</code> table reference
     */
    public Modelli() {
        this(DSL.name("modelli"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Usrbilancio.USRBILANCIO;
    }

    @Override
    public Identity<ModelliRecord, Integer> getIdentity() {
        return (Identity<ModelliRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ModelliRecord> getPrimaryKey() {
        return Keys.KEY_MODELLI_PRIMARY;
    }

    @Override
    public Modelli as(String alias) {
        return new Modelli(DSL.name(alias), this);
    }

    @Override
    public Modelli as(Name alias) {
        return new Modelli(alias, this);
    }

    @Override
    public Modelli as(Table<?> alias) {
        return new Modelli(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Modelli rename(String name) {
        return new Modelli(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Modelli rename(Name name) {
        return new Modelli(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Modelli rename(Table<?> name) {
        return new Modelli(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Modelli where(Condition condition) {
        return new Modelli(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Modelli where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Modelli where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Modelli where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Modelli where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Modelli where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Modelli where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Modelli where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Modelli whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Modelli whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
