/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables;


import it.usr.web.usrbilancio.domain.Indexes;
import it.usr.web.usrbilancio.domain.Keys;
import it.usr.web.usrbilancio.domain.Usrbilancio;
import it.usr.web.usrbilancio.domain.tables.Allegato.AllegatoPath;
import it.usr.web.usrbilancio.domain.tables.Codice.CodicePath;
import it.usr.web.usrbilancio.domain.tables.Competenza.CompetenzaPath;
import it.usr.web.usrbilancio.domain.tables.Ordinativo.OrdinativoPath;
import it.usr.web.usrbilancio.domain.tables.TipoDocumento.TipoDocumentoPath;
import it.usr.web.usrbilancio.domain.tables.TipoRts.TipoRtsPath;
import it.usr.web.usrbilancio.domain.tables.records.OrdinativoRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ordinativo extends TableImpl<OrdinativoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>usrbilancio.ordinativo</code>
     */
    public static final Ordinativo ORDINATIVO = new Ordinativo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrdinativoRecord> getRecordType() {
        return OrdinativoRecord.class;
    }

    /**
     * The column <code>usrbilancio.ordinativo.id</code>.
     */
    public final TableField<OrdinativoRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.id_competenza</code>.
     */
    public final TableField<OrdinativoRecord, Integer> ID_COMPETENZA = createField(DSL.name("id_competenza"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.id_tipo_documento</code>.
     */
    public final TableField<OrdinativoRecord, Integer> ID_TIPO_DOCUMENTO = createField(DSL.name("id_tipo_documento"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>usrbilancio.ordinativo.id_tipo_rts</code>.
     */
    public final TableField<OrdinativoRecord, Integer> ID_TIPO_RTS = createField(DSL.name("id_tipo_rts"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.id_codice</code>.
     */
    public final TableField<OrdinativoRecord, Integer> ID_CODICE = createField(DSL.name("id_codice"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.numero_pagamento</code>.
     */
    public final TableField<OrdinativoRecord, String> NUMERO_PAGAMENTO = createField(DSL.name("numero_pagamento"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.data_pagamento</code>.
     */
    public final TableField<OrdinativoRecord, LocalDate> DATA_PAGAMENTO = createField(DSL.name("data_pagamento"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.numero_documento</code>.
     */
    public final TableField<OrdinativoRecord, String> NUMERO_DOCUMENTO = createField(DSL.name("numero_documento"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.data_documento</code>.
     */
    public final TableField<OrdinativoRecord, LocalDate> DATA_DOCUMENTO = createField(DSL.name("data_documento"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>usrbilancio.ordinativo.data_ricevimento</code>.
     */
    public final TableField<OrdinativoRecord, LocalDate> DATA_RICEVIMENTO = createField(DSL.name("data_ricevimento"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>usrbilancio.ordinativo.beneficiario</code>.
     */
    public final TableField<OrdinativoRecord, String> BENEFICIARIO = createField(DSL.name("beneficiario"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.descrizione_rts</code>.
     */
    public final TableField<OrdinativoRecord, String> DESCRIZIONE_RTS = createField(DSL.name("descrizione_rts"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.importo</code>.
     */
    public final TableField<OrdinativoRecord, BigDecimal> IMPORTO = createField(DSL.name("importo"), SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.importo_cons</code>.
     */
    public final TableField<OrdinativoRecord, BigDecimal> IMPORTO_CONS = createField(DSL.name("importo_cons"), SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.note</code>.
     */
    public final TableField<OrdinativoRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.rts_completo</code>.
     */
    public final TableField<OrdinativoRecord, Byte> RTS_COMPLETO = createField(DSL.name("rts_completo"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.rts_stampato</code>.
     */
    public final TableField<OrdinativoRecord, Byte> RTS_STAMPATO = createField(DSL.name("rts_stampato"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.fattura_numero</code>.
     */
    public final TableField<OrdinativoRecord, String> FATTURA_NUMERO = createField(DSL.name("fattura_numero"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.fattura_data</code>.
     */
    public final TableField<OrdinativoRecord, LocalDate> FATTURA_DATA = createField(DSL.name("fattura_data"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>usrbilancio.ordinativo.importo_iva</code>.
     */
    public final TableField<OrdinativoRecord, BigDecimal> IMPORTO_IVA = createField(DSL.name("importo_iva"), SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.ordinativo_iva</code>.
     */
    public final TableField<OrdinativoRecord, Integer> ORDINATIVO_IVA = createField(DSL.name("ordinativo_iva"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>usrbilancio.ordinativo.importo_ritenuta</code>.
     */
    public final TableField<OrdinativoRecord, BigDecimal> IMPORTO_RITENUTA = createField(DSL.name("importo_ritenuta"), SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.ordinativo_ritenuta</code>.
     */
    public final TableField<OrdinativoRecord, Integer> ORDINATIVO_RITENUTA = createField(DSL.name("ordinativo_ritenuta"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>usrbilancio.ordinativo.consolidamento</code>. 0=non
     * impostato,1=da consolidare,2=consolidato
     */
    public final TableField<OrdinativoRecord, Byte> CONSOLIDAMENTO = createField(DSL.name("consolidamento"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "0=non impostato,1=da consolidare,2=consolidato");

    /**
     * The column <code>usrbilancio.ordinativo.noterag</code>.
     */
    public final TableField<OrdinativoRecord, String> NOTERAG = createField(DSL.name("noterag"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>usrbilancio.ordinativo.flag</code>. 0 = nulla\n1 =
     * commissario\n2 = f24/ritenuta caricato e in attesa di ortes conclusivo
     */
    public final TableField<OrdinativoRecord, Integer> FLAG = createField(DSL.name("flag"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "0 = nulla\\n1 = commissario\\n2 = f24/ritenuta caricato e in attesa di ortes conclusivo");

    /**
     * The column <code>usrbilancio.ordinativo.versione</code>.
     */
    public final TableField<OrdinativoRecord, Long> VERSIONE = createField(DSL.name("versione"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    private Ordinativo(Name alias, Table<OrdinativoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Ordinativo(Name alias, Table<OrdinativoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>usrbilancio.ordinativo</code> table reference
     */
    public Ordinativo(String alias) {
        this(DSL.name(alias), ORDINATIVO);
    }

    /**
     * Create an aliased <code>usrbilancio.ordinativo</code> table reference
     */
    public Ordinativo(Name alias) {
        this(alias, ORDINATIVO);
    }

    /**
     * Create a <code>usrbilancio.ordinativo</code> table reference
     */
    public Ordinativo() {
        this(DSL.name("ordinativo"), null);
    }

    public <O extends Record> Ordinativo(Table<O> path, ForeignKey<O, OrdinativoRecord> childPath, InverseForeignKey<O, OrdinativoRecord> parentPath) {
        super(path, childPath, parentPath, ORDINATIVO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrdinativoPath extends Ordinativo implements Path<OrdinativoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrdinativoPath(Table<O> path, ForeignKey<O, OrdinativoRecord> childPath, InverseForeignKey<O, OrdinativoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrdinativoPath(Name alias, Table<OrdinativoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrdinativoPath as(String alias) {
            return new OrdinativoPath(DSL.name(alias), this);
        }

        @Override
        public OrdinativoPath as(Name alias) {
            return new OrdinativoPath(alias, this);
        }

        @Override
        public OrdinativoPath as(Table<?> alias) {
            return new OrdinativoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Usrbilancio.USRBILANCIO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ORDINATIVO_FK_ORDINATIVO_ANNUALITA_IDX, Indexes.ORDINATIVO_FK_ORDINATIVO_CODICE_IDX, Indexes.ORDINATIVO_FK_ORDINATIVO_TIPODOCUMENTO_IDX, Indexes.ORDINATIVO_FK_ORDINATIVO_TIPORTS_IDX, Indexes.ORDINATIVO_FK_SELF_ORDINATIVO_IVA_IDX, Indexes.ORDINATIVO_FK_SELF_ORDINATIVO_RITENUTA_IDX);
    }

    @Override
    public Identity<OrdinativoRecord, Integer> getIdentity() {
        return (Identity<OrdinativoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrdinativoRecord> getPrimaryKey() {
        return Keys.KEY_ORDINATIVO_PRIMARY;
    }

    @Override
    public List<ForeignKey<OrdinativoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ORDINATIVO_COMPETENZA, Keys.FK_ORDINATIVO_TIPODOCUMENTO, Keys.FK_ORDINATIVO_TIPORTS, Keys.FK_ORDINATIVO_CODICE, Keys.FK_SELF_ORDINATIVO_IVA, Keys.FK_SELF_ORDINATIVO_RITENUTA);
    }

    private transient CompetenzaPath _competenza;

    /**
     * Get the implicit join path to the <code>usrbilancio.competenza</code>
     * table.
     */
    public CompetenzaPath competenza() {
        if (_competenza == null)
            _competenza = new CompetenzaPath(this, Keys.FK_ORDINATIVO_COMPETENZA, null);

        return _competenza;
    }

    private transient TipoDocumentoPath _tipoDocumento;

    /**
     * Get the implicit join path to the <code>usrbilancio.tipo_documento</code>
     * table.
     */
    public TipoDocumentoPath tipoDocumento() {
        if (_tipoDocumento == null)
            _tipoDocumento = new TipoDocumentoPath(this, Keys.FK_ORDINATIVO_TIPODOCUMENTO, null);

        return _tipoDocumento;
    }

    private transient TipoRtsPath _tipoRts;

    /**
     * Get the implicit join path to the <code>usrbilancio.tipo_rts</code>
     * table.
     */
    public TipoRtsPath tipoRts() {
        if (_tipoRts == null)
            _tipoRts = new TipoRtsPath(this, Keys.FK_ORDINATIVO_TIPORTS, null);

        return _tipoRts;
    }

    private transient CodicePath _codice;

    /**
     * Get the implicit join path to the <code>usrbilancio.codice</code> table.
     */
    public CodicePath codice() {
        if (_codice == null)
            _codice = new CodicePath(this, Keys.FK_ORDINATIVO_CODICE, null);

        return _codice;
    }

    private transient OrdinativoPath _fkSelfOrdinativoIva;

    /**
     * Get the implicit join path to the <code>usrbilancio.ordinativo</code>
     * table, via the <code>fk_self_ordinativo_iva</code> key.
     */
    public OrdinativoPath fkSelfOrdinativoIva() {
        if (_fkSelfOrdinativoIva == null)
            _fkSelfOrdinativoIva = new OrdinativoPath(this, Keys.FK_SELF_ORDINATIVO_IVA, null);

        return _fkSelfOrdinativoIva;
    }

    private transient OrdinativoPath _fkSelfOrdinativoRitenuta;

    /**
     * Get the implicit join path to the <code>usrbilancio.ordinativo</code>
     * table, via the <code>fk_self_ordinativo_ritenuta</code> key.
     */
    public OrdinativoPath fkSelfOrdinativoRitenuta() {
        if (_fkSelfOrdinativoRitenuta == null)
            _fkSelfOrdinativoRitenuta = new OrdinativoPath(this, Keys.FK_SELF_ORDINATIVO_RITENUTA, null);

        return _fkSelfOrdinativoRitenuta;
    }

    private transient AllegatoPath _allegato;

    /**
     * Get the implicit to-many join path to the
     * <code>usrbilancio.allegato</code> table
     */
    public AllegatoPath allegato() {
        if (_allegato == null)
            _allegato = new AllegatoPath(this, null, Keys.FK_ALLEGATO_ORDINATIVO.getInverseKey());

        return _allegato;
    }

    @Override
    public Ordinativo as(String alias) {
        return new Ordinativo(DSL.name(alias), this);
    }

    @Override
    public Ordinativo as(Name alias) {
        return new Ordinativo(alias, this);
    }

    @Override
    public Ordinativo as(Table<?> alias) {
        return new Ordinativo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ordinativo rename(String name) {
        return new Ordinativo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ordinativo rename(Name name) {
        return new Ordinativo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ordinativo rename(Table<?> name) {
        return new Ordinativo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ordinativo where(Condition condition) {
        return new Ordinativo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ordinativo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ordinativo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ordinativo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ordinativo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ordinativo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ordinativo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ordinativo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ordinativo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ordinativo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
