/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables;


import it.usr.web.usrbilancio.domain.Keys;
import it.usr.web.usrbilancio.domain.Usrbilancio;
import it.usr.web.usrbilancio.domain.tables.records.ParametriRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Parametri extends TableImpl<ParametriRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>usrbilancio.parametri</code>
     */
    public static final Parametri PARAMETRI = new Parametri();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParametriRecord> getRecordType() {
        return ParametriRecord.class;
    }

    /**
     * The column <code>usrbilancio.parametri.parametro</code>.
     */
    public final TableField<ParametriRecord, String> PARAMETRO = createField(DSL.name("parametro"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.parametri.valore</code>.
     */
    public final TableField<ParametriRecord, String> VALORE = createField(DSL.name("valore"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.parametri.descrizione</code>.
     */
    public final TableField<ParametriRecord, String> DESCRIZIONE = createField(DSL.name("descrizione"), SQLDataType.VARCHAR(255), this, "");

    private Parametri(Name alias, Table<ParametriRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Parametri(Name alias, Table<ParametriRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>usrbilancio.parametri</code> table reference
     */
    public Parametri(String alias) {
        this(DSL.name(alias), PARAMETRI);
    }

    /**
     * Create an aliased <code>usrbilancio.parametri</code> table reference
     */
    public Parametri(Name alias) {
        this(alias, PARAMETRI);
    }

    /**
     * Create a <code>usrbilancio.parametri</code> table reference
     */
    public Parametri() {
        this(DSL.name("parametri"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Usrbilancio.USRBILANCIO;
    }

    @Override
    public UniqueKey<ParametriRecord> getPrimaryKey() {
        return Keys.KEY_PARAMETRI_PRIMARY;
    }

    @Override
    public Parametri as(String alias) {
        return new Parametri(DSL.name(alias), this);
    }

    @Override
    public Parametri as(Name alias) {
        return new Parametri(alias, this);
    }

    @Override
    public Parametri as(Table<?> alias) {
        return new Parametri(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Parametri rename(String name) {
        return new Parametri(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Parametri rename(Name name) {
        return new Parametri(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Parametri rename(Table<?> name) {
        return new Parametri(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Parametri where(Condition condition) {
        return new Parametri(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Parametri where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Parametri where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Parametri where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Parametri where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Parametri where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Parametri where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Parametri where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Parametri whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Parametri whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
