/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain.tables;


import it.usr.web.usrbilancio.domain.Indexes;
import it.usr.web.usrbilancio.domain.Keys;
import it.usr.web.usrbilancio.domain.Usrbilancio;
import it.usr.web.usrbilancio.domain.tables.Anagrafica.AnagraficaPath;
import it.usr.web.usrbilancio.domain.tables.Ordinativo.OrdinativoPath;
import it.usr.web.usrbilancio.domain.tables.records.RitenutaRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 *     
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ritenuta extends TableImpl<RitenutaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>usrbilancio.ritenuta</code>
     */
    public static final Ritenuta RITENUTA = new Ritenuta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RitenutaRecord> getRecordType() {
        return RitenutaRecord.class;
    }

    /**
     * The column <code>usrbilancio.ritenuta.id</code>.
     */
    public final TableField<RitenutaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>usrbilancio.ritenuta.id_ordinativo</code>.
     */
    public final TableField<RitenutaRecord, Integer> ID_ORDINATIVO = createField(DSL.name("id_ordinativo"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ritenuta.id_anagrafica</code>.
     */
    public final TableField<RitenutaRecord, Integer> ID_ANAGRAFICA = createField(DSL.name("id_anagrafica"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ritenuta.imponibile</code>.
     */
    public final TableField<RitenutaRecord, BigDecimal> IMPONIBILE = createField(DSL.name("imponibile"), SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>usrbilancio.ritenuta.cassa</code>.
     */
    public final TableField<RitenutaRecord, BigDecimal> CASSA = createField(DSL.name("cassa"), SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>usrbilancio.ritenuta.spese_anticipo</code>.
     */
    public final TableField<RitenutaRecord, BigDecimal> SPESE_ANTICIPO = createField(DSL.name("spese_anticipo"), SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>usrbilancio.ritenuta.iva</code>.
     */
    public final TableField<RitenutaRecord, BigDecimal> IVA = createField(DSL.name("iva"), SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>usrbilancio.ritenuta.perc_ritenute_operate</code>.
     */
    public final TableField<RitenutaRecord, BigDecimal> PERC_RITENUTE_OPERATE = createField(DSL.name("perc_ritenute_operate"), SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>usrbilancio.ritenuta.perc_irap_versata</code>.
     */
    public final TableField<RitenutaRecord, BigDecimal> PERC_IRAP_VERSATA = createField(DSL.name("perc_irap_versata"), SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>usrbilancio.ritenuta.versione</code>.
     */
    public final TableField<RitenutaRecord, Long> VERSIONE = createField(DSL.name("versione"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    private Ritenuta(Name alias, Table<RitenutaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Ritenuta(Name alias, Table<RitenutaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>usrbilancio.ritenuta</code> table reference
     */
    public Ritenuta(String alias) {
        this(DSL.name(alias), RITENUTA);
    }

    /**
     * Create an aliased <code>usrbilancio.ritenuta</code> table reference
     */
    public Ritenuta(Name alias) {
        this(alias, RITENUTA);
    }

    /**
     * Create a <code>usrbilancio.ritenuta</code> table reference
     */
    public Ritenuta() {
        this(DSL.name("ritenuta"), null);
    }

    public <O extends Record> Ritenuta(Table<O> path, ForeignKey<O, RitenutaRecord> childPath, InverseForeignKey<O, RitenutaRecord> parentPath) {
        super(path, childPath, parentPath, RITENUTA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RitenutaPath extends Ritenuta implements Path<RitenutaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RitenutaPath(Table<O> path, ForeignKey<O, RitenutaRecord> childPath, InverseForeignKey<O, RitenutaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RitenutaPath(Name alias, Table<RitenutaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RitenutaPath as(String alias) {
            return new RitenutaPath(DSL.name(alias), this);
        }

        @Override
        public RitenutaPath as(Name alias) {
            return new RitenutaPath(alias, this);
        }

        @Override
        public RitenutaPath as(Table<?> alias) {
            return new RitenutaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Usrbilancio.USRBILANCIO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RITENUTA_FK_RITENUTA_ANAGRAFICA_IDX, Indexes.RITENUTA_FK_RITENUTA_ORDINATIVO_IDX, Indexes.RITENUTA_RITENUTA_UQ);
    }

    @Override
    public Identity<RitenutaRecord, Integer> getIdentity() {
        return (Identity<RitenutaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RitenutaRecord> getPrimaryKey() {
        return Keys.KEY_RITENUTA_PRIMARY;
    }

    @Override
    public List<ForeignKey<RitenutaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_RITENUTA_ORDINATIVO, Keys.FK_RITENUTA_ANAGRAFICA);
    }

    private transient OrdinativoPath _ordinativo;

    /**
     * Get the implicit join path to the <code>usrbilancio.ordinativo</code>
     * table.
     */
    public OrdinativoPath ordinativo() {
        if (_ordinativo == null)
            _ordinativo = new OrdinativoPath(this, Keys.FK_RITENUTA_ORDINATIVO, null);

        return _ordinativo;
    }

    private transient AnagraficaPath _anagrafica;

    /**
     * Get the implicit join path to the <code>usrbilancio.anagrafica</code>
     * table.
     */
    public AnagraficaPath anagrafica() {
        if (_anagrafica == null)
            _anagrafica = new AnagraficaPath(this, Keys.FK_RITENUTA_ANAGRAFICA, null);

        return _anagrafica;
    }

    @Override
    public Ritenuta as(String alias) {
        return new Ritenuta(DSL.name(alias), this);
    }

    @Override
    public Ritenuta as(Name alias) {
        return new Ritenuta(alias, this);
    }

    @Override
    public Ritenuta as(Table<?> alias) {
        return new Ritenuta(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ritenuta rename(String name) {
        return new Ritenuta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ritenuta rename(Name name) {
        return new Ritenuta(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ritenuta rename(Table<?> name) {
        return new Ritenuta(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ritenuta where(Condition condition) {
        return new Ritenuta(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ritenuta where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ritenuta where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ritenuta where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ritenuta where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ritenuta where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ritenuta where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ritenuta where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ritenuta whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ritenuta whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
