/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain;


import it.usr.web.usrbilancio.domain.tables.Allegato;
import it.usr.web.usrbilancio.domain.tables.AllegatoCodice;
import it.usr.web.usrbilancio.domain.tables.Competenza;
import it.usr.web.usrbilancio.domain.tables.MovimentiVirtuali;
import it.usr.web.usrbilancio.domain.tables.Ordinativo;
import it.usr.web.usrbilancio.domain.tables.OrdinativoAppoggio;
import it.usr.web.usrbilancio.domain.tables.Quietanza;
import it.usr.web.usrbilancio.domain.tables.Richiesta;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in usrbilancio.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ALLEGATO_FK_ALLEGATO_ORDINATIVO_IDX = Internal.createIndex(DSL.name("fk_allegato_ordinativo_idx"), Allegato.ALLEGATO, new OrderField[] { Allegato.ALLEGATO.ID_ORDINATIVO }, false);
    public static final Index ALLEGATO_CODICE_FK_ALLEGATOCODICE_CODICE_IDX = Internal.createIndex(DSL.name("fk_allegatocodice_codice_idx"), AllegatoCodice.ALLEGATO_CODICE, new OrderField[] { AllegatoCodice.ALLEGATO_CODICE.ID_CODICE }, false);
    public static final Index COMPETENZA_FK_ANNUALITA_CAPITOLO_IDX = Internal.createIndex(DSL.name("fk_annualita_capitolo_idx"), Competenza.COMPETENZA, new OrderField[] { Competenza.COMPETENZA.ID_CAPITOLO }, false);
    public static final Index ORDINATIVO_FK_ORDINATIVO_ANNUALITA_IDX = Internal.createIndex(DSL.name("fk_ordinativo_annualita_idx"), Ordinativo.ORDINATIVO, new OrderField[] { Ordinativo.ORDINATIVO.ID_COMPETENZA }, false);
    public static final Index ORDINATIVO_FK_ORDINATIVO_CODICE_IDX = Internal.createIndex(DSL.name("fk_ordinativo_codice_idx"), Ordinativo.ORDINATIVO, new OrderField[] { Ordinativo.ORDINATIVO.ID_CODICE }, false);
    public static final Index ORDINATIVO_FK_ORDINATIVO_TIPODOCUMENTO_IDX = Internal.createIndex(DSL.name("fk_ordinativo_tipodocumento_idx"), Ordinativo.ORDINATIVO, new OrderField[] { Ordinativo.ORDINATIVO.ID_TIPO_DOCUMENTO }, false);
    public static final Index ORDINATIVO_FK_ORDINATIVO_TIPORTS_IDX = Internal.createIndex(DSL.name("fk_ordinativo_tiports_idx"), Ordinativo.ORDINATIVO, new OrderField[] { Ordinativo.ORDINATIVO.ID_TIPO_RTS }, false);
    public static final Index ORDINATIVO_APPOGGIO_FK_ORDINATIVOAPP_CODICE_IDX = Internal.createIndex(DSL.name("fk_ordinativoapp_codice_idx"), OrdinativoAppoggio.ORDINATIVO_APPOGGIO, new OrderField[] { OrdinativoAppoggio.ORDINATIVO_APPOGGIO.ID_CODICE }, false);
    public static final Index ORDINATIVO_APPOGGIO_FK_ORDINATIVOAPP_COMPETENZA_IDX = Internal.createIndex(DSL.name("fk_ordinativoapp_competenza_idx"), OrdinativoAppoggio.ORDINATIVO_APPOGGIO, new OrderField[] { OrdinativoAppoggio.ORDINATIVO_APPOGGIO.ID_COMPETENZA }, false);
    public static final Index ORDINATIVO_APPOGGIO_FK_ORDINATIVOAPP_TIPODOCUMENTO_IDX = Internal.createIndex(DSL.name("fk_ordinativoapp_tipodocumento_idx"), OrdinativoAppoggio.ORDINATIVO_APPOGGIO, new OrderField[] { OrdinativoAppoggio.ORDINATIVO_APPOGGIO.ID_TIPO_DOCUMENTO }, false);
    public static final Index ORDINATIVO_APPOGGIO_FK_ORDINATIVOAPP_TIPORTS_IDX = Internal.createIndex(DSL.name("fk_ordinativoapp_tiports_idx"), OrdinativoAppoggio.ORDINATIVO_APPOGGIO, new OrderField[] { OrdinativoAppoggio.ORDINATIVO_APPOGGIO.ID_TIPO_RTS }, false);
    public static final Index MOVIMENTI_VIRTUALI_FK_PREVENTRATA_CODICE_IDX = Internal.createIndex(DSL.name("fk_preventrata_codice_idx"), MovimentiVirtuali.MOVIMENTI_VIRTUALI, new OrderField[] { MovimentiVirtuali.MOVIMENTI_VIRTUALI.ID_CODICE }, false);
    public static final Index MOVIMENTI_VIRTUALI_FK_PREVENTRATA_COMPETENZA_IDX = Internal.createIndex(DSL.name("fk_preventrata_competenza_idx"), MovimentiVirtuali.MOVIMENTI_VIRTUALI, new OrderField[] { MovimentiVirtuali.MOVIMENTI_VIRTUALI.ID_COMPETENZA }, false);
    public static final Index QUIETANZA_FK_QUIETANZA_CODICE_IDX = Internal.createIndex(DSL.name("fk_quietanza_codice_idx"), Quietanza.QUIETANZA, new OrderField[] { Quietanza.QUIETANZA.ID_CODICE }, false);
    public static final Index QUIETANZA_FK_QUIETANZA_COMPETENZA_IDX = Internal.createIndex(DSL.name("fk_quietanza_competenza_idx"), Quietanza.QUIETANZA, new OrderField[] { Quietanza.QUIETANZA.ID_COMPETENZA }, false);
    public static final Index QUIETANZA_FK_QUIETANZA_TIPODOCUMENTO_IDX = Internal.createIndex(DSL.name("fk_quietanza_tipodocumento_idx"), Quietanza.QUIETANZA, new OrderField[] { Quietanza.QUIETANZA.ID_TIPO_DOCUMENTO }, false);
    public static final Index QUIETANZA_FK_QUIETANZA_TIPORTS_IDX = Internal.createIndex(DSL.name("fk_quietanza_tiports_idx"), Quietanza.QUIETANZA, new OrderField[] { Quietanza.QUIETANZA.ID_TIPO_RTS }, false);
    public static final Index RICHIESTA_FK_RICHIESTA_COMPETENZA_IDX = Internal.createIndex(DSL.name("fk_richiesta_competenza_idx"), Richiesta.RICHIESTA, new OrderField[] { Richiesta.RICHIESTA.ID_COMPETENZA }, false);
    public static final Index ORDINATIVO_FK_SELF_ORDINATIVO_IVA_IDX = Internal.createIndex(DSL.name("fk_self_ordinativo_iva_idx"), Ordinativo.ORDINATIVO, new OrderField[] { Ordinativo.ORDINATIVO.ORDINATIVO_IVA }, false);
    public static final Index ORDINATIVO_FK_SELF_ORDINATIVO_RITENUTA_IDX = Internal.createIndex(DSL.name("fk_self_ordinativo_ritenuta_idx"), Ordinativo.ORDINATIVO, new OrderField[] { Ordinativo.ORDINATIVO.ORDINATIVO_RITENUTA }, false);
}
