/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain;


import it.usr.web.usrbilancio.domain.tables.Allegato;
import it.usr.web.usrbilancio.domain.tables.AllegatoAppoggio;
import it.usr.web.usrbilancio.domain.tables.AllegatoCodice;
import it.usr.web.usrbilancio.domain.tables.Anagrafica;
import it.usr.web.usrbilancio.domain.tables.Capitolo;
import it.usr.web.usrbilancio.domain.tables.Codice;
import it.usr.web.usrbilancio.domain.tables.Competenza;
import it.usr.web.usrbilancio.domain.tables.Comune;
import it.usr.web.usrbilancio.domain.tables.LogOperazioni;
import it.usr.web.usrbilancio.domain.tables.MimeType;
import it.usr.web.usrbilancio.domain.tables.Modelli;
import it.usr.web.usrbilancio.domain.tables.MovimentiVirtuali;
import it.usr.web.usrbilancio.domain.tables.Ordinativo;
import it.usr.web.usrbilancio.domain.tables.OrdinativoAppoggio;
import it.usr.web.usrbilancio.domain.tables.Parametri;
import it.usr.web.usrbilancio.domain.tables.Quietanza;
import it.usr.web.usrbilancio.domain.tables.RettificaIva;
import it.usr.web.usrbilancio.domain.tables.Richiesta;
import it.usr.web.usrbilancio.domain.tables.Ritenuta;
import it.usr.web.usrbilancio.domain.tables.TipoDocumento;
import it.usr.web.usrbilancio.domain.tables.TipoRts;
import it.usr.web.usrbilancio.domain.tables.Utente;


/**
 * Convenience access to all tables in usrbilancio.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>usrbilancio.allegato</code>.
     */
    public static final Allegato ALLEGATO = Allegato.ALLEGATO;

    /**
     * The table <code>usrbilancio.allegato_appoggio</code>.
     */
    public static final AllegatoAppoggio ALLEGATO_APPOGGIO = AllegatoAppoggio.ALLEGATO_APPOGGIO;

    /**
     * The table <code>usrbilancio.allegato_codice</code>.
     */
    public static final AllegatoCodice ALLEGATO_CODICE = AllegatoCodice.ALLEGATO_CODICE;

    /**
     * The table <code>usrbilancio.anagrafica</code>.
     */
    public static final Anagrafica ANAGRAFICA = Anagrafica.ANAGRAFICA;

    /**
     * The table <code>usrbilancio.capitolo</code>.
     */
    public static final Capitolo CAPITOLO = Capitolo.CAPITOLO;

    /**
     * The table <code>usrbilancio.codice</code>.
     */
    public static final Codice CODICE = Codice.CODICE;

    /**
     * The table <code>usrbilancio.competenza</code>.
     */
    public static final Competenza COMPETENZA = Competenza.COMPETENZA;

    /**
     * The table <code>usrbilancio.comune</code>.
     */
    public static final Comune COMUNE = Comune.COMUNE;

    /**
     * The table <code>usrbilancio.log_operazioni</code>.
     */
    public static final LogOperazioni LOG_OPERAZIONI = LogOperazioni.LOG_OPERAZIONI;

    /**
     * The table <code>usrbilancio.mime_type</code>.
     */
    public static final MimeType MIME_TYPE = MimeType.MIME_TYPE;

    /**
     * The table <code>usrbilancio.modelli</code>.
     */
    public static final Modelli MODELLI = Modelli.MODELLI;

    /**
     * The table <code>usrbilancio.movimenti_virtuali</code>.
     */
    public static final MovimentiVirtuali MOVIMENTI_VIRTUALI = MovimentiVirtuali.MOVIMENTI_VIRTUALI;

    /**
     * The table <code>usrbilancio.ordinativo</code>.
     */
    public static final Ordinativo ORDINATIVO = Ordinativo.ORDINATIVO;

    /**
     * The table <code>usrbilancio.ordinativo_appoggio</code>.
     */
    public static final OrdinativoAppoggio ORDINATIVO_APPOGGIO = OrdinativoAppoggio.ORDINATIVO_APPOGGIO;

    /**
     * The table <code>usrbilancio.parametri</code>.
     */
    public static final Parametri PARAMETRI = Parametri.PARAMETRI;

    /**
     * The table <code>usrbilancio.quietanza</code>.
     */
    public static final Quietanza QUIETANZA = Quietanza.QUIETANZA;

    /**
     * The table <code>usrbilancio.rettifica_iva</code>.
     */
    public static final RettificaIva RETTIFICA_IVA = RettificaIva.RETTIFICA_IVA;

    /**
     * The table <code>usrbilancio.richiesta</code>.
     */
    public static final Richiesta RICHIESTA = Richiesta.RICHIESTA;

    /**
     * The table <code>usrbilancio.ritenuta</code>.
     */
    public static final Ritenuta RITENUTA = Ritenuta.RITENUTA;

    /**
     * The table <code>usrbilancio.tipo_documento</code>.
     */
    public static final TipoDocumento TIPO_DOCUMENTO = TipoDocumento.TIPO_DOCUMENTO;

    /**
     * The table <code>usrbilancio.tipo_rts</code>.
     */
    public static final TipoRts TIPO_RTS = TipoRts.TIPO_RTS;

    /**
     * The table <code>usrbilancio.utente</code>.
     */
    public static final Utente UTENTE = Utente.UTENTE;
}
