/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usrbilancio.domain;


import it.usr.web.usrbilancio.domain.tables.Allegato;
import it.usr.web.usrbilancio.domain.tables.AllegatoAppoggio;
import it.usr.web.usrbilancio.domain.tables.AllegatoCodice;
import it.usr.web.usrbilancio.domain.tables.Anagrafica;
import it.usr.web.usrbilancio.domain.tables.Capitolo;
import it.usr.web.usrbilancio.domain.tables.Codice;
import it.usr.web.usrbilancio.domain.tables.Competenza;
import it.usr.web.usrbilancio.domain.tables.LogOperazioni;
import it.usr.web.usrbilancio.domain.tables.MimeType;
import it.usr.web.usrbilancio.domain.tables.Modelli;
import it.usr.web.usrbilancio.domain.tables.MovimentiVirtuali;
import it.usr.web.usrbilancio.domain.tables.Ordinativo;
import it.usr.web.usrbilancio.domain.tables.OrdinativoAppoggio;
import it.usr.web.usrbilancio.domain.tables.Parametri;
import it.usr.web.usrbilancio.domain.tables.Quietanza;
import it.usr.web.usrbilancio.domain.tables.RettificaIva;
import it.usr.web.usrbilancio.domain.tables.Richiesta;
import it.usr.web.usrbilancio.domain.tables.TipoDocumento;
import it.usr.web.usrbilancio.domain.tables.TipoRts;
import it.usr.web.usrbilancio.domain.tables.Utente;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Usrbilancio extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>usrbilancio</code>
     */
    public static final Usrbilancio USRBILANCIO = new Usrbilancio();

    /**
     * The table <code>usrbilancio.allegato</code>.
     */
    public final Allegato ALLEGATO = Allegato.ALLEGATO;

    /**
     * The table <code>usrbilancio.allegato_appoggio</code>.
     */
    public final AllegatoAppoggio ALLEGATO_APPOGGIO = AllegatoAppoggio.ALLEGATO_APPOGGIO;

    /**
     * The table <code>usrbilancio.allegato_codice</code>.
     */
    public final AllegatoCodice ALLEGATO_CODICE = AllegatoCodice.ALLEGATO_CODICE;

    /**
     * The table <code>usrbilancio.anagrafica</code>.
     */
    public final Anagrafica ANAGRAFICA = Anagrafica.ANAGRAFICA;

    /**
     * The table <code>usrbilancio.capitolo</code>.
     */
    public final Capitolo CAPITOLO = Capitolo.CAPITOLO;

    /**
     * The table <code>usrbilancio.codice</code>.
     */
    public final Codice CODICE = Codice.CODICE;

    /**
     * The table <code>usrbilancio.competenza</code>.
     */
    public final Competenza COMPETENZA = Competenza.COMPETENZA;

    /**
     * The table <code>usrbilancio.log_operazioni</code>.
     */
    public final LogOperazioni LOG_OPERAZIONI = LogOperazioni.LOG_OPERAZIONI;

    /**
     * The table <code>usrbilancio.mime_type</code>.
     */
    public final MimeType MIME_TYPE = MimeType.MIME_TYPE;

    /**
     * The table <code>usrbilancio.modelli</code>.
     */
    public final Modelli MODELLI = Modelli.MODELLI;

    /**
     * The table <code>usrbilancio.movimenti_virtuali</code>.
     */
    public final MovimentiVirtuali MOVIMENTI_VIRTUALI = MovimentiVirtuali.MOVIMENTI_VIRTUALI;

    /**
     * The table <code>usrbilancio.ordinativo</code>.
     */
    public final Ordinativo ORDINATIVO = Ordinativo.ORDINATIVO;

    /**
     * The table <code>usrbilancio.ordinativo_appoggio</code>.
     */
    public final OrdinativoAppoggio ORDINATIVO_APPOGGIO = OrdinativoAppoggio.ORDINATIVO_APPOGGIO;

    /**
     * The table <code>usrbilancio.parametri</code>.
     */
    public final Parametri PARAMETRI = Parametri.PARAMETRI;

    /**
     * The table <code>usrbilancio.quietanza</code>.
     */
    public final Quietanza QUIETANZA = Quietanza.QUIETANZA;

    /**
     * The table <code>usrbilancio.rettifica_iva</code>.
     */
    public final RettificaIva RETTIFICA_IVA = RettificaIva.RETTIFICA_IVA;

    /**
     * The table <code>usrbilancio.richiesta</code>.
     */
    public final Richiesta RICHIESTA = Richiesta.RICHIESTA;

    /**
     * The table <code>usrbilancio.tipo_documento</code>.
     */
    public final TipoDocumento TIPO_DOCUMENTO = TipoDocumento.TIPO_DOCUMENTO;

    /**
     * The table <code>usrbilancio.tipo_rts</code>.
     */
    public final TipoRts TIPO_RTS = TipoRts.TIPO_RTS;

    /**
     * The table <code>usrbilancio.utente</code>.
     */
    public final Utente UTENTE = Utente.UTENTE;

    /**
     * No further instances allowed
     */
    private Usrbilancio() {
        super("usrbilancio", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Allegato.ALLEGATO,
            AllegatoAppoggio.ALLEGATO_APPOGGIO,
            AllegatoCodice.ALLEGATO_CODICE,
            Anagrafica.ANAGRAFICA,
            Capitolo.CAPITOLO,
            Codice.CODICE,
            Competenza.COMPETENZA,
            LogOperazioni.LOG_OPERAZIONI,
            MimeType.MIME_TYPE,
            Modelli.MODELLI,
            MovimentiVirtuali.MOVIMENTI_VIRTUALI,
            Ordinativo.ORDINATIVO,
            OrdinativoAppoggio.ORDINATIVO_APPOGGIO,
            Parametri.PARAMETRI,
            Quietanza.QUIETANZA,
            RettificaIva.RETTIFICA_IVA,
            Richiesta.RICHIESTA,
            TipoDocumento.TIPO_DOCUMENTO,
            TipoRts.TIPO_RTS,
            Utente.UTENTE
        );
    }
}
